services:
    keycloak_db:
        image: postgres:latest
        container_name: keycloak_db
        env_file: ".env"
        ports:
            - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
    keycloak:
        image: quay.io/keycloak/keycloak:26.0.7
        container_name: keycloak
        command: start-dev
        env_file: ".env"
        ports:
            - "8080:8080"
        environment:
            - KC_DB=postgres
            - KC_DB_URL_HOST=keycloak_db
            - KC_DB_USERNAME=${POSTGRES_USER}
            - KC_DB_PASSWORD=${POSTGRES_PASSWORD}

volumes:
    postgres_data:
